# Generated by Django 4.1.9 on 2023-10-19 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=100)),
                ("job_description", models.CharField(max_length=300)),
                ("posted_date", models.DateField()),
                ("location", models.CharField(max_length=100)),
                ("vacancy", models.PositiveIntegerField()),
                ("job_nature", models.CharField(max_length=100)),
                ("salary", models.PositiveIntegerField()),
                ("application_date", models.DateField()),
                ("skills_req", models.CharField(max_length=300)),
                ("experience", models.PositiveIntegerField()),
                ("education", models.CharField(max_length=100)),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyDetails",
            fields=[
                ("company_id", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=100)),
                ("company_ceo_name", models.CharField(max_length=100)),
                ("company_mail", models.EmailField(max_length=254)),
                ("company_site", models.URLField()),
                ("company_description", models.TextField(blank=True, null=True)),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                ("company_linkedin", models.URLField(blank=True, null=True)),
                (
                    "company_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("starting_year", models.DateField()),
                ("employees", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
