# Generated by Django 4.1.9 on 2023-10-19 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0002_jobpost_companydetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("mailid", models.EmailField(max_length=254)),
                ("linkedin", models.URLField(blank=True)),
                ("githublink", models.URLField(blank=True)),
                ("skills", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(max_length=255)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, upload_to="profile_pics/"),
                ),
                ("resume", models.FileField(blank=True, upload_to="resumes/")),
                ("dateofbirth", models.DateField()),
                ("about", models.TextField(blank=True)),
                ("phone_no", models.CharField(blank=True, max_length=15)),
                ("gender", models.CharField(max_length=10)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
