# Generated by Django 4.1.9 on 2023-10-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_userdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companydetails",
            name="company_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="companydetails",
            name="user_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="company_id",
            field=models.IntegerField(),
        ),
    ]
